name: tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  pytest:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .
          pip install pytest>=8.0.0 pytest-cov>=4.0.0 pytest-order>=1.0.0 coverage==7.8.0 faker==37.5.0 fastjsonschema==2.20.0 numpy>=2.0.0 bcrypt==4.3.0 requests==2.32.3

      - name: Run tests
        run: |
          pytest --maxfail=1 --disable-warnings -q


